 Site settings
 title: "My Project Euler Solutions"
 description: "A journal of my solutions to Project Euler problems"
 url: "https://aspenxdev.github.io/Solving-Project-Euler-Problems/"
 theme: "minimal-mistakes-jekyll"
 author:
  name: "Victor"
  email: "ayechanvictor@gmail.com"

# Settings for social media
# social:
#  github: "https://github.com/AspenXDev>"
#  twitter: "https://twitter.com/AspenXDev" Maybe create a Twitter/X account?

# Optional plugins for Jekyll
plugins:
  - jekyll-seo-tag # Adds SEO tags
  - jekyll-feed # Adds RSS feed to the site

permalink: "pretty" # 'clean URLs (e.g., /about instead of /about.html)
markdown: kramdown # default

exclude:
  - README.md